### PR TITLE
Update main.rs

### PR DESCRIPTION
**Pull request by AnthonyBuisset**

### CODE REVIEW

**Review by Bernardstanislas — APPROVED** [review]

**Review by ofux — APPROVED** [review]

**Comment by Bernardstanislas** [comment]
This item belongs to payment request #3201D2 on [OnlyDust](https://www.onlydust.xyz/):
* from [tokio-rs](https://www.onlydust.xyz/) to [AnthonyBuisset](https://www.onlydust.xyz/)
* 11 items included
* $1,000 for 2 days of work

**Comment by Bernardstanislas** [comment]
This item belongs to payment request #A722F0 on [OnlyDust](https://www.onlydust.xyz/):
* from [tokio-rs](https://www.onlydust.xyz/) to [AnthonyBuisset](https://www.onlydust.xyz/)
* 11 items included
* $1,000 for 2 days of work

**Comment by Bernardstanislas** [comment]
> This item belongs to payment request #3201D2 on [OnlyDust](https://www.onlydust.xyz/):
> * from [tokio-rs](https://www.onlydust.xyz/) to [AnthonyBuisset](https://www.onlydust.xyz/)
> * 11 items included
> * $1,000 for 2 days of work

Payment request #A722F0 has been processed and payment is complete. See you around on [OnlyDust](https://www.onlydust.xyz/).

**Comment by Bernardstanislas** [comment]
This item belongs to payment request #BF807D on [OnlyDust](https://www.onlydust.xyz/):
* from [tokio-rs](https://www.onlydust.xyz/) to [AnthonyBuisset](https://www.onlydust.xyz/)
* 11 items included
* $1,000 for 2 days of work

**Comment by Bernardstanislas** [comment]
> This item belongs to payment request #3201D2 on [OnlyDust](https://www.onlydust.xyz/):
> * from [tokio-rs](https://www.onlydust.xyz/) to [AnthonyBuisset](https://www.onlydust.xyz/)
> * 11 items included
> * $1,000 for 2 days of work

Payment request #BF807D has been processed and payment is complete. See you around on [OnlyDust](https://www.onlydust.xyz/).

**Comment by Bernardstanislas** [comment]
This item belongs to payment request #B9EDBB on [OnlyDust](https://www.onlydust.xyz/):
* from [tokio-rs](https://www.onlydust.xyz/) to [AnthonyBuisset](https://www.onlydust.xyz/)
* 11 items included
* $1,000 for 2 days of work

**Comment by Bernardstanislas** [comment]
> This item belongs to payment request #BF807D on [OnlyDust](https://www.onlydust.xyz/):
> * from [tokio-rs](https://www.onlydust.xyz/) to [AnthonyBuisset](https://www.onlydust.xyz/)
> * 11 items included
> * $1,000 for 2 days of work

Payment request #B9EDBB has been processed and payment is complete. See you around on [OnlyDust](https://www.onlydust.xyz/).

**Comment by Bernardstanislas** [comment]
This item belongs to payment request #922A6C on [OnlyDust](https://www.onlydust.xyz/):
* from [tokio-rs](https://www.onlydust.xyz/) to [AnthonyBuisset](https://www.onlydust.xyz/)
* 11 items included
* $1,000 for 2 days of work

**Comment by Bernardstanislas** [comment]
> > This item belongs to payment request #BF807D on [OnlyDust](https://www.onlydust.xyz/):
> > * from [tokio-rs](https://www.onlydust.xyz/) to [AnthonyBuisset](https://www.onlydust.xyz/)
> > * 11 items included
> > * $1,000 for 2 days of work
> 
> Payment request #B9EDBB has been processed and payment is complete. See you around on [OnlyDust](https://www.onlydust.xyz/).

Payment request #922A6C has been processed and payment is complete. See you around on [OnlyDust](https://www.onlydust.xyz/).

**Pull request merged**
